### ISSUE TITLE
Forsub not working 

### ISSUE THREAD

**Issue by hagadmansa** [EvamariaTG/EvaMaria#205]
Forcesub is not working in /link, /plink, /batch and /pbatch please fix it ass soon as possible.

**Comment by subinps** [comment]
Fixed https://github.com/EvamariaTG/EvaMaria/commit/a85a4a97c56c1eff696e70379a6ee051d4780925

**Comment by hagadmansa** [comment]
![9951E4BF-539E-4947-8A82-13ACF1CE80CF](https://user-images.githubusercontent.com/95907824/162507174-c9e783d6-57e8-46f3-b895-e89cdec9894d.png) still not workingbro showing this error when i enables force sub.
